In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import GridSearchCV
from pyod.models.ocsvm import OCSVM
from pyod.models.pca import PCA
from pyod.models.knn import KNN
from pyod.models.iforest import IForest
from pyod.utils.data import evaluate_print
import time




In [3]:
# Load and preprocess the dataset for training
df_train = pd.read_csv('train1.csv')  # Replace 'your_train_dataset.csv' with the actual file name
train_data = df_train.drop(['Time', 'BLANK1', 'BLANK2', 'BLANK3'], axis=1)
train_data.dropna(axis=0, inplace=True)
X_train = train_data.values


In [4]:
# Define the range of hyperparameters for each model
#ocsvm_params = {'nu': [0.1, 0.3, 0.5]}
ocsvm_params = {'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto'], 'nu': [0.1, 0.2, 0.3]}
pca_params = {'n_components': [2, 4, 6]}
knn_params = {'n_neighbors': [3, 5, 7, 9 ]}
iforest_params = {'n_estimators': [50, 100, 150]}

# Perform hyperparameter tuning using grid search
models = {'OCSVM': (OCSVM(), ocsvm_params),
          'PCA': (PCA(), pca_params),
          'kNN': (KNN(), knn_params),
          'Isolation Forest': (IForest(), iforest_params)}

best_models = {}

for model_name, (model, param_grid) in models.items():
    grid_search = GridSearchCV(model, param_grid, scoring='accuracy', cv=5)
    grid_search.fit(X_train)
    best_model = grid_search.best_estimator_
    best_models[model_name] = best_model

# Assign the best models to variables
best_ocsvm = best_models['OCSVM']
best_pca = best_models['PCA']
best_knn = best_models['kNN']
best_iforest = best_models['Isolation Forest']



C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:

C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:

C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:

C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py", line 685, in _score
    scores = scorer(estimator, X_test)
TypeError: __call__() missing 1 required positional argument: 'y_true'

  UserWarning,
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_search.py:925: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  category=UserWarning
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\sklearn\model_selection\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\py36\lib\site-pack

In [5]:
# Load and preprocess the test datasets
df_test_01 = pd.read_csv('test1.csv')  # Replace 'your_test_dataset_01.csv' with the actual file name
df_test_02 = pd.read_csv('test2.csv')  # Replace 'your_test_dataset_02.csv' with the actual file name
test_data_01 = df_test_01.drop(['Time', 'BLANK1', 'BLANK2', 'BLANK3'], axis=1)
test_data_02 = df_test_02.drop(['Time', 'BLANK1', 'BLANK2', 'BLANK3'], axis=1)
test_data_01.dropna(axis=0, inplace=True)
test_data_02.dropna(axis=0, inplace=True)
X_test_01 = test_data_01.values
X_test_02 = test_data_02.values



In [6]:
# Perform anomaly detection and calculate metrics for Test Dataset 1
# Initialize dictionaries to store the metrics and prediction times
metrics_01 = {'OCSVM': {}, 'PCA': {}, 'kNN': {}, 'Isolation Forest': {}}
prediction_times_01 = {'OCSVM': 0, 'PCA': 0, 'kNN': 0, 'Isolation Forest': 0}

for model_name, model in [('OCSVM', best_ocsvm), ('PCA', best_pca), ('kNN', best_knn), ('Isolation Forest', best_iforest)]:
    start_time = time.time()
    y_pred_01 = model.predict(X_test_01)
    end_time = time.time()
    prediction_time = end_time - start_time

    prediction_times_01[model_name] = prediction_time
    prediction_times_01[model_name] = round(prediction_time, 4)  # Round to 4 decimal places


    y_true_01 = np.ones_like(y_pred_01)
    tn, fp, fn, tp = confusion_matrix(y_true_01, y_pred_01, labels=[0, 1]).ravel()
    fpr = fp / (fp + tn)
    
    print(y_pred_01)
    print(y_true_01)
    metrics_01[model_name]['Accuracy'] = accuracy_score(y_true_01, y_pred_01)
    metrics_01[model_name]['Precision'] = precision_score(y_true_01, y_pred_01)
    metrics_01[model_name]['Recall'] = recall_score(y_true_01, y_pred_01)
    metrics_01[model_name]['F1 Score'] = f1_score(y_true_01, y_pred_01)
    metrics_01[model_name]['False Positive Rate'] = fpr

    metrics_01[model_name]['Accuracy'] = round(metrics_01[model_name]['Accuracy'], 6)  # Round to 6 decimal places
    metrics_01[model_name]['Precision'] = round(metrics_01[model_name]['Precision'], 6)  # Round to 6 decimal places
    metrics_01[model_name]['Recall'] = round(metrics_01[model_name]['Recall'], 6)  # Round to 6 decimal places
    metrics_01[model_name]['F1 Score'] = round(metrics_01[model_name]['F1 Score'], 6)  # Round to 6 decimal places
    metrics_01[model_name]['False Positive Rate'] = round(fpr, 6)  # Round to 6 decimal places



C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in longlong_scalars
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in longlong_scalars


[0 0 0 ... 1 1 1]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[0 0 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]


C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in longlong_scalars
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in longlong_scalars


In [7]:
# Perform anomaly detection and calculate metrics for Test Dataset 2
# Initialize dictionaries to store the metrics
metrics_02 = {'OCSVM': {}, 'PCA': {}, 'kNN': {}, 'Isolation Forest': {}}
prediction_times_02 = {'OCSVM': 0, 'PCA': 0, 'kNN': 0, 'Isolation Forest': 0}

# Calculate metrics for each model
for model_name, model in [('OCSVM', best_ocsvm), ('PCA', best_pca), ('kNN', best_knn), ('Isolation Forest', best_iforest)]:
    start_time = time.time()
    y_pred_02 = model.predict(X_test_02)
    end_time = time.time()
    prediction_time = end_time - start_time

    prediction_times_02[model_name] = prediction_time
    prediction_times_02[model_name] = round(prediction_time, 4)  # Round to 4 decimal places


    y_true_02 = np.ones_like(y_pred_02)
    tn, fp, fn, tp = confusion_matrix(y_true_02, y_pred_02, labels=[0, 1]).ravel()
    fpr = fp / (fp + tn)
    
    metrics_02[model_name]['Accuracy'] = accuracy_score(y_true_02, y_pred_02)
    metrics_02[model_name]['Precision'] = precision_score(y_true_02, y_pred_02)
    metrics_02[model_name]['Recall'] = recall_score(y_true_02, y_pred_02)
    metrics_02[model_name]['F1 Score'] = f1_score(y_true_02, y_pred_02)
    metrics_02[model_name]['False Positive Rate'] = fpr
    metrics_02[model_name]['Accuracy'] = round(metrics_02[model_name]['Accuracy'], 6)  # Round to 6 decimal places
    metrics_02[model_name]['Precision'] = round(metrics_02[model_name]['Precision'], 6)  # Round to 6 decimal places
    metrics_02[model_name]['Recall'] = round(metrics_02[model_name]['Recall'], 6)  # Round to 6 decimal places
    metrics_02[model_name]['F1 Score'] = round(metrics_02[model_name]['F1 Score'], 6)  # Round to 6 decimal places
    metrics_02[model_name]['False Positive Rate'] = round(fpr, 6)  # Round to 6 decimal places




C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in longlong_scalars
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in longlong_scalars
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in longlong_scalars
C:\ProgramData\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in longlong_scalars


In [8]:
# Print the results
print("Results for Test Dataset 1:")
for model_name, metrics in metrics_01.items():
    print(model_name)
    for metric_name, value in metrics.items():
        print(metric_name + ":", value)
    print("Prediction Time:", prediction_times_01[model_name],"seconds")
    print()

print("Results for Test Dataset 2:")
for model_name, metrics in metrics_02.items():
    print(model_name)
    for metric_name, value in metrics.items():
        print(metric_name + ":", value)
    print("Prediction Time:", prediction_times_02[model_name],"seconds")
    print()


Results for Test Dataset 1:
OCSVM
Accuracy: 0.99393
Precision: 1.0
Recall: 0.99393
F1 Score: 0.996956
False Positive Rate: nan
Prediction Time: 0.047 seconds

PCA
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
False Positive Rate: nan
Prediction Time: 0.0 seconds

kNN
Accuracy: 0.998403
Precision: 1.0
Recall: 0.998403
F1 Score: 0.999201
False Positive Rate: nan
Prediction Time: 0.2339 seconds

Isolation Forest
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
False Positive Rate: nan
Prediction Time: 0.0625 seconds

Results for Test Dataset 2:
OCSVM
Accuracy: 0.906897
Precision: 1.0
Recall: 0.906897
F1 Score: 0.951175
False Positive Rate: nan
Prediction Time: 0.002 seconds

PCA
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
False Positive Rate: nan
Prediction Time: 0.001 seconds

kNN
Accuracy: 0.991379
Precision: 1.0
Recall: 0.991379
F1 Score: 0.995671
False Positive Rate: nan
Prediction Time: 0.0453 seconds

Isolation Forest
Accuracy: 0.824138
Precision: 1.0
Recal